
#baseURL = "/"
baseURL = "https://inflection-quant.pages.dev/"
#baseURL = "https://yourusername.github.io/"
relativeURLs = true
canonifyURLs = false

languageCode = "en-us"
title = "Inflection Quant Lab"
theme = "PaperMod"

[params]
  math = true
  # mainSections = ["articles/quant-foundations", "articles/quant-engineering"]
  mainSections = ["articles"]
  ShowPostsOnHomePage = false
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  googleSiteVerification = "of2Pz27K05bYIg57IYeeBpTRO7kneF7_0SNINDKhJCk" 


[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 1
