baseURL = "https://leslie-ren.github.io/Inflection.Quant/"
relativeURLs = false
canonifyURLs = false
languageCode = "en-us"
title = "Inflection Quant Solutions"
theme = "PaperMod"

[params]
  math = true
  mainSections = ["articles/quant-foundations", "articles/quant-engineering"]
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[menu]
[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 1
